Some QoL features and fixes
aniyomiorg/aniyomi pull request #1132
Opened 2023-09-23 13:21 UTC by Samfun75

Add extension settings to Anime/Manga screen
Register recent anime updates widget
Fix pressing "View Episodes" crashing app or opening random manga

2023-09-25 13:14 UTC, jmir1 requested changes

2023-09-25 13:14 UTC, jmir1 commented on app/src/main/java/eu/kanade/presentation/entries/manga/MangaScreen.kt
> +import eu.kanade.tachiyomi.ui.browse.anime.extension.details.SourcePreferencesScreen
that doesn't seem right

2023-09-25 18:12 UTC, Samfun75 commented on app/src/main/java/eu/kanade/presentation/entries/manga/MangaScreen.kt
> +import eu.kanade.tachiyomi.ui.browse.anime.extension.details.SourcePreferencesScreen
Not it does not 😅

2023-09-26 09:44 UTC, jmir1 approved these changes

2023-09-26 09:45 UTC, merged