chore: remove aniyomiorg/aniyomi-extensions
aniyomiorg/aniyomi pull request #1617
Opened 2024-06-19 11:58 UTC by Secozzi

Same rationale as removing the official manga extensions, people are just going to end up using extensions they don't know how to/shouldn't use, and i can confirm at least one extension will be maintained elsewhere.

Note: ISSUE_TEMPLATE.md is removed in #1601 so it isn't changed here

2024-06-19 12:01 UTC, hollowshiroyuki commented
so you confirm you'll maintain jellyfish elsewhere ? provide link at least 💢

2024-06-19 14:35 UTC, abdallahmehiz requested changes
Sorry, secco

2024-06-19 14:35 UTC, abdallahmehiz commented on .github/ISSUE_TEMPLATE/report_issue.yml
> +        - label: If this is an issue with an anime extension, I should be opening an issue in the extensions repository.
It should be "extension's"

2024-06-19 14:35 UTC, abdallahmehiz commented on .github/ISSUE_TEMPLATE/request_feature.yml
> +        - label: If this is an issue with an extension, I should be opening an issue in the extensions repository.
Here too

2024-06-20 10:48 UTC, abdallahmehiz submitted a review, later dismissed

2024-07-02 15:30 UTC, abdallahmehiz approved these changes

2024-07-03 19:40 UTC, closed without merging

2024-07-03 20:24 UTC, hollowshiroyuki commented
rest in piss you won't be missed